name: dfrog_htmx
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  http: ^1.3.0
  sqlite3: ^2.7.4
  html_template: ^0.3.0
  cron: ^0.6.1
  sse: ^4.1.7

dev_dependencies:
  build_runner: ^2.4.11
  mocktail: ^1.0.3
  test: ^1.25.5
  mason_cli: ^0.1.2